{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  annotations:
    {{- range $key, $value := .Values.web.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: {{ .Values.web.service.port }}
  {{- if .Values.web.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.web.ingress.host }}
      secretName: {{ .Values.web.ingress.tlsSecret }}
  {{- end }}
{{- end }}
