apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-tier
  namespace: prod
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: tier-app-api-external-sercret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::082168422974:role/tier-app-access-ssm-3tier-app
  name: tier-app-api-external-sercret
  namespace: prod
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-cred
  namespace: prod
spec:
  refreshInterval: 48h
  secretStoreRef:
    name: secretstore-tier
    kind: SecretStore
  target:
    name: tier-api-sercret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: tier-app-username
  - secretKey: password
    remoteRef:
      key: tier-app-password


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api
  namespace: datadog
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: secretstore-tier
    kind: SecretStore
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: datadog-api
